image: node:latest

stages:
    - install
    - test
    - build
    - prepublish

install:
    stage: install
    artifacts:
        paths:
            - node_modules/
        expire_in: 1 week
    script:
        # - npm ci
        - echo "TODO: finish later..."
# test:
#     stage: test
#     when: always
#     coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
#     artifacts:
#         paths:
#             - coverage/
#     script:
#         - npm run coverage

# build:
#     stage: build
#     artifacts:
#         paths:
#             - dist/
#         expire_in: 1 week
#     script:
#         - npm run build

# prepublish:
#     stage: prepublish
#     script:
#         - npm publish ./dist --dry-run
