version: 2.1

jobs:
    install:
        docker:
            - image: cimg/node:current
        steps:
            - checkout
            - restore_cache:
                  keys:
                      # when lock file changes, use increasingly general patterns to restore cache
                      - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
                      - node-v1-{{ .Branch }}-
                      - node-v1-
            - run:
                  name: 'Say hello'
                  command: 'npm ci'
            - save_cache:
                  paths:
                      - ~/usr/local/lib/node_modules # location depends on npm version
                  key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}

    test_unit:
        docker:
            - image: cimg/node:current
        steps:
            - checkout
            - restore_cache:
                  keys:
                      # when lock file changes, use increasingly general patterns to restore cache
                      - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
                      - node-v1-{{ .Branch }}-
                      - node-v1-
            - run:
                  name: 'Unit Test'
                  command: 'npm run test:unit'

workflows:
    install:
        jobs:
            - install
    tests:
        jobs:
            - test_unit
