version: 2.1

jobs:
    install_test_job:
        docker:
            - image: cimg/node:current
        steps:
            - checkout
            - run:
                  name: 'Installing & Running Tests'
                  command: |
                      npm ci
                      npm run test:unit

workflows:
    install_test_workflow:
        jobs:
            - install_test_job
