version: 2.1

jobs:
    install:
        docker:
            - image: cimg/node:current
        steps:
            - checkout
            - run:
                  name: 'Install Dependencies'
                  command: 'npm ci'

    test_unit:
        docker:
            - image: cimg/node:current
        steps:
            - checkout
            - run:
                  name: 'Unit Test'
                  command: 'npm run test:unit'

workflows:
    install:
        jobs:
            - install
            - test_unit
