version: 2.1

jobs:
    main_build_job:
        docker:
            - image: cimg/node:current
        steps:
            - checkout
            - run:
                  name: 'Installing Dependencies'
                  command: npm ci
            - run:
                  name: 'Running Unit Tests'
                  command: npm run test:coverage
                  environment:
                      JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
            - store_test_results:
                  path: /reports/junit

workflows:
    main_build_workflow:
        jobs:
            - main_build_job
