version: 2.1

jobs:
    install_test_job:
        docker:
            - image: cimg/node:current
        steps:
            - checkout
            - run:
                  name: 'Installing Dependencies'
                  command: npm ci
            - run:
                  name: 'Running Unit Tests'
                  command: npm run test:unit
            - store_test_results:
                  path: coverage

workflows:
    install_test_workflow:
        jobs:
            - install_test_job
