version: 2.1

jobs:
    main_build_job:
        docker:
            - image: cimg/node:current
        steps:
            - checkout
            - run:
                  name: 'Installing Dependencies'
                  command: npm ci
            - run:
                  name: 'Running Unit Tests'
                  command: npm run test:ci-coverage
                  environment:
                      JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
            - run:
                  name: 'Uploading Code Coverage'
                  command: npm run coveralls
                  environment:
                      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
                      COVERALLS_SERVICE_NAME: ${{ secrets.COVERALLS_SERVICE_NAME }}
                      COVERALLS_GIT_BRANCH: ${{ secrets.COVERALLS_GIT_BRANCH }}
            - store_test_results:
                  path: ./reports/junit/
            # - store_artifacts:
            #       path: coverage

workflows:
    main_build_workflow:
        jobs:
            - main_build_job
