version: 2.1

jobs:
    install:
        docker:
            - image: cimg/node:current
        working_directory: /temp
        steps:
            - checkout
            - run:
                  name: 'Say hello'
                  command: 'npm ci'
            - store_artifacts:
                  path: /node_modules
    test_unit:
        docker:
            - image: cimg/node:current
        working_directory: /temp
        steps:
            - checkout
            - run:
                  name: 'Unit Test'
                  command: 'npm run test:unit'

    # steps:
    #     - run:
    #           name: Creating Dummy Artifacts
    #           command: |
    #               echo "my artifact file" > /tmp/artifact-1;

    #               echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;

workflows:
    install:
        jobs:
            - install
    tests:
        jobs:
            - test_unit
